from clever_faq.infrastructure.errors.base import InfrastructureError


class RepoError(InfrastructureError): ...


class EntityAddError(InfrastructureError): ...


class RollbackError(InfrastructureError): ...


class FileStorageError(InfrastructureError): ...
