from clever_faq.domain.common.errors import DomainError, DomainFieldError


class WrongUserAccountEmailFormatError(DomainFieldError): ...


class PasswordCantBeEmptyError(DomainFieldError): ...


class UserAccountNameCantBeEmptyError(DomainFieldError): ...


class TooBigUserAccountNameError(DomainFieldError): ...


class TooSmallUserAccountNameError(DomainFieldError): ...


class RoleAssignmentNotPermittedError(DomainError): ...


class BadUserNameError(DomainFieldError): ...


class RoleChangeNotPermittedError(DomainError): ...


class ActivationChangeNotPermittedError(DomainError): ...


class AuthorizationError(DomainError): ...


class BadVkUserError(DomainFieldError): ...
